---
application:
  name: "lab-imob"
  project: "Test Project"
  organization: "TiagoDevWeb"
databases:
- type: "MYSQL"
  name: "imob"
  version: "5.7"
routers:
- name: "main-lab-imob"
  routes:
  - application_name: "lab-imob"
    paths:
    - "/*"
