version: '3'
services:
  app:
    build: ./.docker/
    container_name: ${DC_APP_NAME:-app}
    restart: always
    tty: true
    volumes:
      - .:/var/www
    entrypoint: ./.docker/entrypoint.sh
    networks:
      - lab_imob
    depends_on:
      db: 
        condition: service_healthy
  web:
    build: .docker/nginx/
    container_name: ${DC_WEB_NAME:-web}
    restart: always
    tty: true
    volumes:
      - .:/var/www
    ports:
      - "${PORT:-80}:80"
    networks:
      - lab_imob
    depends_on:
      - app
  db:
    image: mariadb:10.3
    container_name: ${DC_DB_NAME:-db}
    restart: always
    tty: true
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=local"
      - "MYSQL_USER=root"
    volumes:
      - "dbdata:/var/lib/mysql"
    ports:
      - "${DC_DB_PORT:-3306}:3306"
    command: "--innodb_use_native_aio=0"
    healthcheck:
      test: '/usr/bin/mysql --user=root --database=local --execute="SHOW DATABASES;"'
    networks:
      - lab_imob
  dbtest:
    container_name: ${DC_DB_TEST_NAME:-dbtest}
    image: mariadb:10.3
    tmpfs: /var/lib/mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=testing"
      - "MYSQL_USER=root"
    networks:
      - lab_imob
  redis:
    image: redis:alpine
    container_name: ${DC_REDIS_NAME:-redis}
    tty: true
    expose:
      - 6379
    networks:
      - lab_imob
networks: 
  lab_imob:
    driver: bridge
volumes:
  "dbdata":
    driver: local