name: Main
on: push

jobs: 
  build:
    name: Main
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/phpunit
      - uses: ./.github/actions/npm
      - uses: ./.github/actions/jest